version: '3.8'

services:
  docker_state_exporter:
    image: hakikaru/docker_state_exporter:1.5.0
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "8080:8080"
